/// Flutter icons MonobankIcons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MonobankIcons
///      fonts:
///       - asset: fonts/MonobankIcons.ttf
///
/// 
/// * Typicons, (c) Stephen Hutchings 2012
///         Author:    Stephen Hutchings
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://typicons.com/
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class MonobankIcons {
  MonobankIcons._();

  static const _kFontFam = 'MonobankIcons';
  static const String? _kFontPkg = null;

  static const IconData th_large = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData credits = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData credit_card = IconData(0xe8c6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gift_1 = IconData(0xf06b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar_check = IconData(0xf274, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
